language: ruby

rvm:
  - 2.1

notifications:
  irc:
    channels:
      - "irc.freenode.org#nyaa~"
    template:
      - "%{repository}#%{build_number} - %{commit} on %{branch} by %{author}: %{message}"
      - "Build details: %{build_url} - Change view: %{compare_url}"
    skip_join: true
    on_success: change
    on_failure: always
