language: ruby

rvm:
  - 2.1.4

addons:
  postgresql: 9.3

env:
  - TEST_DATABASE_URL='postgresql://postgres@localhost/test'

before_script:
  - psql -c 'CREATE DATABASE test;' -U postgres
  - "echo 'test: { secret_key_base: '$(bundle exec rake secret)' }' > config/secrets.yml"

notifications:
  irc:
    channels:
      - "irc.freenode.org#nyaa~"
    template:
      - "%{repository}#%{build_number} - %{commit} on %{branch} by %{author}: %{message}"
      - "Build details: %{build_url} - Change view: %{compare_url}"
    skip_join: true
    on_success: change
    on_failure: always
